package com.xszheng.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.xszheng.domain.D1Resource;

public interface D1ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_resource
     *
     * @mbg.generated
     */
    int insert(D1Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_resource
     *
     * @mbg.generated
     */
    int insertSelective(D1Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_resource
     *
     * @mbg.generated
     */
    D1Resource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(D1Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(D1Resource record);
    
    /**
     * 根据角色编号来获取相应的资源
     * @author xszheng
     * @date 2018年4月12日下午4:15:38
     * @description
     * @param
     */
    List<D1Resource> listByRoleNo(@Param(value="roleNo") String roleNo);
}