package com.xszheng.mapper;

import com.xszheng.domain.D1ResourceRole;

public interface D1ResourceRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_resource_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_resource_role
     *
     * @mbg.generated
     */
    int insert(D1ResourceRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_resource_role
     *
     * @mbg.generated
     */
    int insertSelective(D1ResourceRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_resource_role
     *
     * @mbg.generated
     */
    D1ResourceRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_resource_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(D1ResourceRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_resource_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(D1ResourceRole record);
}