package com.xszheng.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.xszheng.domain.D1Role;

public interface D1RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_role
     *
     * @mbg.generated
     */
    int insert(D1Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_role
     *
     * @mbg.generated
     */
    int insertSelective(D1Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_role
     *
     * @mbg.generated
     */
    D1Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(D1Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d1_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(D1Role record);
    
    /**
     * 根据用户编号查询所有角色
     * @author xszheng
     * @date 2018年4月12日下午1:15:51
     * @description
     * @param
     */
    List<D1Role> listRolesByUserNo(@Param(value="userNo") String userNo);
    
    /**
     * 获取所有角色
     * @author xszheng
     * @date 2018年4月12日下午4:03:31
     * @description
     * @param
     */
    List<D1Role> listAll();
}