package com.xszheng.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name="d1_resource_role")
public class D1ResourceRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d1_resource_role.id
     *
     * @mbg.generated
     */
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d1_resource_role.role_no
     *
     * @mbg.generated
     */
	@Column(name="role_no")
    private String roleNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d1_resource_role.url_id
     *
     * @mbg.generated
     */
	@Column(name="url_id")
    private String urlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d1_resource_role.update_time
     *
     * @mbg.generated
     */
	@Column(name="update_time")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d1_resource_role.id
     *
     * @return the value of d1_resource_role.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d1_resource_role.id
     *
     * @param id the value for d1_resource_role.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d1_resource_role.role_no
     *
     * @return the value of d1_resource_role.role_no
     *
     * @mbg.generated
     */
    public String getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d1_resource_role.role_no
     *
     * @param roleNo the value for d1_resource_role.role_no
     *
     * @mbg.generated
     */
    public void setRoleNo(String roleNo) {
        this.roleNo = roleNo == null ? null : roleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d1_resource_role.url_id
     *
     * @return the value of d1_resource_role.url_id
     *
     * @mbg.generated
     */
    public String getUrlId() {
        return urlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d1_resource_role.url_id
     *
     * @param urlId the value for d1_resource_role.url_id
     *
     * @mbg.generated
     */
    public void setUrlId(String urlId) {
        this.urlId = urlId == null ? null : urlId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d1_resource_role.update_time
     *
     * @return the value of d1_resource_role.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d1_resource_role.update_time
     *
     * @param updateTime the value for d1_resource_role.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}