package com.xszheng.domain;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name="d1_role")
public class D1Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d1_role.id
     *
     * @mbg.generated
     */
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d1_role.user_no
     *
     * @mbg.generated
     */
	@Column(name="user_no")
    private String userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d1_role.role_no
     *
     * @mbg.generated
     */
	@Column(name="role_no")
    private String roleNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d1_role.role_name
     *
     * @mbg.generated
     */
	@Column(name="role_name")
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d1_role.id
     *
     * @return the value of d1_role.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d1_role.id
     *
     * @param id the value for d1_role.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d1_role.user_no
     *
     * @return the value of d1_role.user_no
     *
     * @mbg.generated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d1_role.user_no
     *
     * @param userNo the value for d1_role.user_no
     *
     * @mbg.generated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d1_role.role_no
     *
     * @return the value of d1_role.role_no
     *
     * @mbg.generated
     */
    public String getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d1_role.role_no
     *
     * @param roleNo the value for d1_role.role_no
     *
     * @mbg.generated
     */
    public void setRoleNo(String roleNo) {
        this.roleNo = roleNo == null ? null : roleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d1_role.role_name
     *
     * @return the value of d1_role.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d1_role.role_name
     *
     * @param roleName the value for d1_role.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}