package com.xszheng.domain;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table
public class D1User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d1_user.id
     *
     * @mbg.generated
     */
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d1_user.user_name
     *
     * @mbg.generated
     */
	@Column(name="user_name")
    private String userName;
	
	/**
	 * 用户No
	 */
	@Column(name="user_no")
	private String userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d1_user.password
     *
     * @mbg.generated
     */
	@Column(name="password")
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d1_user.phone
     *
     * @mbg.generated
     */
	@Column(name="phone")
    private String phone;
	
	/**
	 * 状态：-1-锁定，1-正常
	 */
	@Column(name="status")
	private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d1_user.id
     *
     * @return the value of d1_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d1_user.id
     *
     * @param id the value for d1_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d1_user.user_name
     *
     * @return the value of d1_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d1_user.user_name
     *
     * @param userName the value for d1_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public String getUserNo() {
		return userNo;
	}

	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d1_user.password
     *
     * @return the value of d1_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d1_user.password
     *
     * @param password the value for d1_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d1_user.phone
     *
     * @return the value of d1_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d1_user.phone
     *
     * @param phone the value for d1_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
    
}